carrierwaveuploader/carrierwave-aws

CHANGELOG.md
README.md
carrierwave-aws.gemspec
lib/carrierwave/storage/aws.rb
lib/carrierwave/storage/aws_file.rb
spec/carrierwave/storage/aws_file_spec.rb
spec/carrierwave/storage/aws_spec.rb
spec/features/querying_files_spec.rb
spec/spec_helper.rb

Heya, this is a first attempt at upgrading the gem to use v2 of the aws-sdk gem.
The entire test suite passes, minus one test I've marked as pending. The new version of aws-sdk requires a region to be specified at instantiation of resources and clients, but we currently have a test specifically checking that you can instantiate the connection without **any** credentials. I'd recommend we just delete the test.
Here are some notes:
* `:public_read` is no longer a valid ACL, I've replaced instances in tests with what is valid: `'public-read'`
* I had to introduce a `CarrierWave::SanitizedFile` instance in the `AWSFile` spec since the implementation now relies on the `to_file` defined in it. If needed/wanted, I can keep fiddling with the test doubles and perhaps get this to work without it.
* …

Update aws-sdk to v2

---

lib/carrierwave-aws.rb
spec/carrierwave-aws_spec.rb

Hi,
I've added a test and a fix for the aws_acl lookup issue we talked about in my other pull request. 
Carrierwaves `add_config` does a lot of magic when generating configuration accessors looking up settings starting on an uploader instance with fallback to its class doing a fallback to its superclass. The new `aws_acl` reader is not doing this but I thing it should:
In a rails project for instance I would configure Carrierwave by calling `CarrierWave.configure ...` in an initializer. The configured `aws_acl` is not visible within the `ImageUploader` nor in instances of `ImageUploader` atm. Using the reader methods defined by calling `add_config :aws_acl` but redefining the setter methods will do the trick.
What do you think?

aws_acl should follow the inheritance chain

---

README.md
lib/carrierwave-aws.rb
lib/carrierwave/storage/aws_file.rb
spec/carrierwave-aws_spec.rb
spec/carrierwave/storage/aws_file_spec.rb

Hi,
first of all, thank you very much for your great gem!
I'm working on a small project storing private content like photos in amazon s3 and serving it using authenticated urls. Currently the performance isn't that good at all. Therefor, I added Cloudfront to my project and added some minor changes to carrierwave-aws in order to use the signed urls feature that Cloudfront provides.
In order to not add gem dependancies to carrierwave-aws and for flexibility on the signing part I choose to inject a 'signer' proc into the url generation chain. This way, any kind of urls (except the authenticated urls) can be signed. In the example I use the [cloudfront-signer](https://github.com/58bits/cloudfront-signer) gem.
Please let me know your opinion and feedback.

Support signed urls as required for serving private content through Cloudfront 

---

README.md

Hey!
Feels like  you have invalid syntax for lambda in you documentation.Tried and get `SyntaxError` locally

Fix syntax error in documentation for config.aws_signer

---

README.md

Some minor changes to the README, with a little more detail for installing the gem. Also specifying what to do with fog if it's specified as the storage option in the uploader file. This should make it easier and less confusing for a beginner, if they are switching from fog. First open-source contribution! :smiley:

Adjust README.md, make the installation process more beginner-friendly.

---

CHANGELOG.md
lib/carrierwave/storage/aws_file.rb
spec/features/copying_files_spec.rb

Until now we didn't ensure that the files generated with
`CarrierWave::Storage::AWSFile#copy_to` were given the same ACL
(Access Control List) as the original files.
As explained in https://github.com/sorentwo/carrierwave-aws/issues/81#issue-154100161
the behavior of #copy_to in CarrierWave is use the `fog_public` configuration
option and make files `public-read` (world-accessible) if it is true.
carrierwave-aws uses a different configuration option (`aws_acl`) which
explicitely defines the default ACL for all uploaded files (i.e. `public-read`)
so it makes sense to compare the copied file with the originally uploaded one.
An alternative test method would be to always check that copied files include
an ACL that matches the `aws_acl` but I cannot for the life of me figure out a
way to get …

Ensure that copied files use the same ACL settings

---

carrierwave-aws.gemspec

I ran the specs with carrierwave 1.0.0.beta and it's all green.

Accept carrierwave 1.0.0.beta as dependency

---

lib/carrierwave/storage/aws_file.rb
spec/carrierwave/storage/aws_file_spec.rb

Hi @sorentwo!
Thanks again for this awesome library. 👍
Past weekend I've played around with creating (and afterwards uploading) zip-files of big AWSFile's on a Heroku free tier project. The naive implementation was using AWSFile's `read` method to retrieve the data and passed it to ruby zip. My worker was killed because of it's memory usage almost immediately.  
The current implementation of the `read` method in `CarrierWave::Storage::AWSFile` dumps the S3 object data into memory. [Aws::S3::Object#get](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#get-instance_method) and [Aws::S3::Client#get_object](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#get_object-instance_method) allows to pass a block to read the data in chunks. I've added support of this to …

Add block support to AWSFile read method

---

lib/carrierwave/storage/aws.rb
lib/carrierwave/storage/aws_file.rb
spec/features/deleting_files_spec.rb
spec/features/moving_files_spec.rb
spec/features/storing_files_spec.rb
spec/spec_helper.rb

*updates #18*
I didn't implement the `clean_cache!`-method, as this should be done using Object Lifecycle Management in my opinion. I'm not sure about the `delete_dir!`-method, it was like this in the previous PR.
One unrelated change: there was an unimplemented spec (which left files lying around the s3 bucket after the specs ran) which I marked as pending.
This is a really cool change by the way, as it is now really easy to do direct file uploads to s3, like `refile` does them (uploading to a cache directory, then moving files to final storage location).

Cache store

---

carrierwave-aws.gemspec

update aws to ~> 2.1 because Aws.eager_autoload! was introduced in 2.1.0

---

lib/carrierwave/storage/aws_file.rb
spec/carrierwave/storage/aws_file_spec.rb
spec/features/storing_files_spec.rb

This PR adds support for uploading large files, by using the underlying `#upload_file` instead of `#put`.
It has been previously discussed by others in #83 and #84.
As noted in the [AWS Developer Blog](https://aws.amazon.com/blogs/developer/uploading-files-to-amazon-s3/), this has the following benefits:
- Manages multipart uploads for objects larger than 15MB.
- Correctly opens files in binary mode to avoid encoding issues.
- Uses multiple threads for uploading parts of large objects in parallel.
> I recommend you use #upload_file whenever possible.
In addition, this reduces the memory used by the uploading process. For example, using `#put` with a file that is more than the memory available for the process results in an out-of-memory error. Using `#upload_file` works just fine.
As far …

Support large files, reduce memory usage

---

carrierwave-aws.gemspec

To allow automated tools (such as
LicenseFinder [https://github.com/pivotal/LicenseFinder]) to detect and
report licenses in use by a system and its dependencies.
Further details here: https://github.com/pivotal/LicenseFinder#a-plea-to-package-authors-and-maintainers

Setting license in gem package spec.

---

lib/carrierwave/storage/aws_file.rb
lib/carrierwave/storage/aws_options.rb

This PR does 2 things:
1. Apply aws_options when moving / copying files. In my case this was necessary because I have server_side_encryption enabled, and when the file was moved from cache to store, an error occurred (because writing unencrypted files is forbidden in the bucket policy).
2. Use multipart_copy when moving / copying large files. This speeds up these operations for large files, and is essentially the same `upload_file` does.

Apply configured aws_options when moving / copying files

---

lib/carrierwave/storage/aws_file.rb
spec/carrierwave/storage/aws_file_spec.rb

When `asset_host` is set we construct the `public_url` by concatenating `asset_host` and `path`. However, since the `path` is not URL encoded, fetching the image through the `public_url` may fail when it includes characters like "+" in the filename

URL encode path when constructing `public_url`

---

README.md

Based on https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/stubbing.html
It took me a bit of digging through the code to figure out this would work, but it cuts about 2.5 minutes off our test suite so figured someone else might find it useful to know.

Document config option for using AWS stub_responses during test

---

README.md
lib/carrierwave-aws.rb
lib/carrierwave/storage/aws_file.rb
spec/carrierwave/storage/aws_file_spec.rb

This PR addresses the use-case of serving a private bucket through unsigned cloudfront urls. AWS allows this by creating a policy for a cloudfront origin identity associated to the cloudfront distribution to the s3 bucket.

Add support for serving from private bucket with public cdn

---

README.md

The tip added in https://github.com/sorentwo/carrierwave-aws/pull/136 helped me, but it lacked information to unblock the default settings in the bucket. It took me a few hours to figure it out why I was getting `Access Denied` while the Bucket Policy was allowing ACL change.
I hope this helps other people less experienced with S3 configuration to figure out how to properly configure their S3 Bucket.

adding ACL unblock suggestion to the README file.

---

carrierwave-aws.gemspec

Hi! First of all, thanks for your making this gem! I use this gem in my project!
Yesterday, CarrierWave 2.0.0 was released, so I update the dependency version.

Update carrierwave to < 2.1

---

README.md

Starting from sdk >= 2.x the former example does not work.

README: fix custom AWS endpoint example

---

lib/carrierwave/support/uri_filename.rb

Hello.
When running with Ruby 2.7.0, some warnings about URI.unescape are output.
```
$ bundle exec rspec
Run options:
include {:focus=>true}
exclude {:type=>:feature}
All examples were filtered out; ignoring {:focus=>true}
Randomized with seed 19295
...................................../home/jit-y/dev/.ghq/github.com/sorentwo/carrierwave-aws/lib/carrierwave/support/uri_filename.rb:9: warning: URI.unescape is obsolete
/home/jit-y/dev/.ghq/github.com/sorentwo/carrierwave-aws/lib/carrierwave/support/uri_filename.rb:9: warning: URI.unescape is obsolete
...
Finished in 0.02729 seconds (files took 0.40844 seconds to load)
40 examples, 0 failures
Randomized with seed 19295
```
This is because URI.decode warning is output even if not in verbose mode from ruby ​​2.7.0. …

warning: URI.unescape is obsolete

---

lib/carrierwave-aws.rb
spec/carrierwave-aws_spec.rb

Currently it's possible to set asset_host_public setting in config, but it doesn't get applied. It turns out it only works if set in uploader.

Fix class level asset_host_public config

---

lib/carrierwave/storage/aws_file.rb
spec/carrierwave/storage/aws_file_spec.rb

- Better support for special characters
- According to https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html, there are some characters, such as `+ (Plus)`, that are not necessary to be sanitized but requires special treatment. 
- We have encountered issues with filename containing `+` fails to copy correctly. `S3Object#copy_to` appears to handle this already if the target is a `S3Object`. 
- Utilizing the underlying `S3Object`'s API with the same name seems to make more sense
Hope this makes sense and let me know what you think!

Update implementation of AWSFile#copy_to to use S3Object#copy_to API

---

.github/workflows/test.yml
gemfiles/carrierwave-2.gemfile
gemfiles/carrierwave-3.gemfile
gemfiles/carrierwave-master.gemfile

The content is almost the same as PR#179.
I don't think it's necessary to forcibly bump the Ruby version supported by the Gem.

Improve test CI
